@server = https://supreme-umbrella-5w94pvggx662v9vq-8080.app.github.dev
###
GET {{server}}/api/instrumentos 
###
POST {{server}}/api/instrumentos
Content-Type: application/json

{"nombre": "Quena", "categoria": "viento", "descripcion": "buen instrumento xd"}
###
GET {{server}}/api/musico
###
POST {{server}}/api/musico
Content-Type: application/json

{"nombre": "pxndx"}